package com.payearly.enums;

public enum CombineDiscountType {

	UPFRONT_FOR_SOURCE_REAREND_FOR_TARGET, 
	UPFRONT_FOR_SOURCE_MONTHEND_FOR_TARGET,
	REAREND_FOR_SOURCE_REAREND_FOR_TARGET,
	MONTHEND_FOR_SOURCE_REAREND_FOR_TARGET,
	MONTHEND_FOR_SOURCE_MONTHEND_FOR_TARGET
	
}
